In [5]:
import numpy as np
import time
import sys
lst = [[1,2,3],
       [4,5,6]]
aryld = np.array(lst)
print(aryld)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(aryld.dtype)

int64


In [ ]:
rc=aryld.astype(np.float32)
print(rc)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
print(aryld.itemsize)

8


In [ ]:
print(rc.itemsize)

4


In [ ]:
rc1=aryld.astype(np.float64)
print(rc1.itemsize)
print(rc1.size)

8
6


In [ ]:
print(rc1.ndim)

2


In [ ]:
print(rc1.size)

6


#Tupple of (row,column)

In [ ]:
print(aryld.shape)

(2, 3)


In [ ]:
sc=np.array(9)
print(sc)

9


In [ ]:
print(sc.ndim)

0


In [ ]:
print(sc.shape)

()


In [ ]:
def generator():
  for i in range(10):
    if i%2==False:
      yield i
gen = generator()
print(np.fromiter(gen, dtype=int))

[0 2 4 6 8]


#Arrray with only ones or only zeros

In [ ]:
print(np.ones((6,6)))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#identity matrix with numpy

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#diagonal matrix


In [ ]:
print(np.diag((4,1,3)))

[[4 0 0]
 [0 1 0]
 [0 0 3]]


#printing list with arange function in numpy

In [ ]:
print(np.arange(67,667,8))

[ 67  75  83  91  99 107 115 123 131 139 147 155 163 171 179 187 195 203
 211 219 227 235 243 251 259 267 275 283 291 299 307 315 323 331 339 347
 355 363 371 379 387 395 403 411 419 427 435 443 451 459 467 475 483 491
 499 507 515 523 531 539 547 555 563 571 579 587 595 603 611 619 627 635
 643 651 659]


#spliting a range in eventually spaced value

In [ ]:
print(np.linspace(0., 1., num=9))

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


#Array indexing


In [ ]:
ary=np.array([0,1,2,3,78])
print(ary[3])

3


In [ ]:
ary1=np.array([[4,9,8,16,7],
              [13,15,17,19,21]])

print(ary1[0,1])
print(ary1[-1,-1])
print(ary1[0])#entire first row
print(ary1[:,0])#entire first column
print(ary1[:, :3])#first three columns

9
21
[ 4  9  8 16  7]
[ 4 13]
[[ 4  9  8]
 [13 15 17]]


#comparing computation time of general python list and numpy array

In [ ]:
S = 1000000
l1 = range(S)
l2 = range(S)
a1 = np.arange(S)
a2 = np.arange(S)
# python list
start = time.time()
result = [x+y for x,y in zip(l1,l2)]
print("Python list took time:",(time.time()-start)*1000)
#numpy array
start = time.time()
result = a1+a2
print("Numpy array took time:",(time.time()-start)*1000)

Python list took time: 126.70636177062988
Numpy array took time: 20.032644271850586


#making complex data type of an array and printing it

In [ ]:
a=np.array([[1,2], [3,4], [5,6]], dtype=complex)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


#reshaping an array in numpy

In [ ]:
print(ary1.shape)
print(ary1.reshape(5,2))  # reshaping the array


(2, 5)
[[ 4  9]
 [ 8 16]
 [ 7 13]
 [15 17]
 [19 21]]


#transforming 2D  array to 1D array and other functions

In [ ]:
print(ary1.ravel())
print(ary1.min())
print(ary1.max())
print(ary1.sum())
print(ary1.sum(axis=0))
print(ary1.sum(axis=1))
print(np.sqrt(ary1))
print(np.std(ary1))

[ 4  9  8 16  7 13 15 17 19 21]
4
21
129
[17 24 25 35 28]
[44 85]
[[2.         3.         2.82842712 4.         2.64575131]
 [3.60555128 3.87298335 4.12310563 4.35889894 4.58257569]]
5.356304696336832


In [ ]:
ary2=np.array([[2,3],
               [4,5]])
ary3=np.array([[8,9],
               [6,7]])
ary4=np.array([[29,23],
               [19,17]])
ary5=np.array([[56,45],
               [78,99]])
print(ary2.dot(ary3))

[[34 39]
 [62 71]]


In [ ]:
print(ary1[0:2,2])
print(ary1[-1])
print(ary1[-1,0:2])
for row in ary1:
  print(row)
for cell in ary1.flat:
  print(cell)
print(np.vstack((ary2,ary3,ary4,ary5)))

[ 8 17]
[13 15 17 19 21]
[13 15]
[ 4  9  8 16  7]
[13 15 17 19 21]
4
9
8
16
7
13
15
17
19
21
[[ 2  3]
 [ 4  5]
 [ 8  9]
 [ 6  7]
 [29 23]
 [19 17]
 [56 45]
 [78 99]]


In [7]:
abc=np.arange(30).reshape(2,15)
print(abc)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [10]:
print(np.hsplit(abc,3))
print(np.vsplit(abc,2))

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [16]:
ab=np.arange(12).reshape(3,4)
print(ab)
ab1 = ab>4
print(ab1)
print(ab[ab1])
ab[ab1]=-1
print(ab)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


In [17]:
for row in ab:
  for cell in row:
    print(cell)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1


In [18]:
for cell in ab.flatten():
  print(cell)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1


In [19]:
for x in np.nditer(ab,order='C'):
  print(x)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1


In [20]:
for x in np.nditer(ab,order='F'):
  print(x)

0
4
-1
1
-1
-1
2
-1
-1
3
-1
-1


In [21]:
for x in np.nditer(ab,order='F',flags=['external_loop']):
  print(x)

[ 0  4 -1]
[ 1 -1 -1]
[ 2 -1 -1]
[ 3 -1 -1]


In [23]:
for x in np.nditer(ab,op_flags=['readwrite']):
  x[...]=x*x
print(ab)

[[ 0  1  4  9]
 [16  1  1  1]
 [ 1  1  1  1]]


In [24]:
for x,y in np.nditer([ab,ab1]):
  print(x,y)

0 False
1 False
4 False
9 False
16 False
1 True
1 True
1 True
1 True
1 True
1 True
1 True
